"use client";
/* i18n resolver (D7). English is the source; Kinyarwanda overlays it.
   Two sources merge into the catalog:
     - content keys (journey/service/agency/question) from locales/{en,rw}.json
       (generated by data/migrate.mjs; migrate preserves rw translations)
     - UI-chrome keys (ui.*) maintained here in code (not touched by migrate)
   t(key, fallback) = rw[key] (if non-empty) -> en[key] -> fallback. */
import { createContext, useContext, useState, type ReactNode } from "react";
import en from "@data/locales/en.json";
import rw from "@data/locales/rw.json";

export type Locale = "en" | "rw";

// UI chrome strings (first-pass Kinyarwanda — flagged for native review).
const UI: Record<Locale, Record<string, string>> = {
  en: {
    "ui.goal.title": "What do you want to do?",
    "ui.goal.sub": "Tell us the life event — we'll map the whole path, including the steps people usually don't know about, and how they depend on each other.",
    "ui.goal.orpick": "Or pick one",
    "ui.goal.continue": "Continue →",
    "ui.goal.search": 'e.g. "open a restaurant" or "transfer a plot to my name"',
    "ui.wiz.goal": "Your goal", "ui.wiz.questions": "A few questions", "ui.wiz.journey": "Your journey",
    "ui.q.sub": "Your answers change which steps apply, what it costs, and how long it takes.",
    "ui.q.back": "← Back", "ui.q.next": "See my journey →", "ui.yes": "Yes", "ui.no": "No",
    "ui.topbar.citizen": "Citizen", "ui.topbar.agent": "Agent",
    "ui.bar.steps": "Steps", "ui.bar.missed": "Easy to forget", "ui.bar.days": "Days",
    "ui.bar.some": "Some", "ui.bar.free": "Free", "ui.bar.fees": "fees", "ui.bar.nofees": "no fees",
    "ui.bar.progress": "Track my progress",
    "ui.node.step": "Step", "ui.chip.free": "Free", "ui.chip.fee": "Has a fee", "ui.chip.missed": "easy to forget",
    "ui.detail.needfirst": "You need to finish first", "ui.detail.bring": "Bring / arrange yourself",
    "ui.detail.goodtoknow": "Good to know", "ui.detail.opensup": "This opens up",
    "ui.detail.cost": "Cost", "ui.detail.howlong": "How long",
    "ui.detail.markdone": "✓ Mark this step done", "ui.detail.markundone": "↩ Mark as not done",
  },
  rw: {
    "ui.goal.title": "Urashaka gukora iki?",
    "ui.goal.sub": "Tubwire icyo ushaka gukora — tuzakwereka inzira yose, harimo n'intambwe abantu benshi batamenya, n'uko zishingikirana.",
    "ui.goal.orpick": "Cyangwa hitamo kimwe",
    "ui.goal.continue": "Komeza →",
    "ui.goal.search": 'urugero: "gufungura resitora" cyangwa "kwandukura isambu mu izina ryanjye"',
    "ui.wiz.goal": "Intego yawe", "ui.wiz.questions": "Ibibazo bike", "ui.wiz.journey": "Urugendo rwawe",
    "ui.q.sub": "Ibisubizo byawe bihindura intambwe zikenewe, igiciro, n'igihe bizatwara.",
    "ui.q.back": "← Subira inyuma", "ui.q.next": "Reba urugendo rwanjye →", "ui.yes": "Yego", "ui.no": "Oya",
    "ui.topbar.citizen": "Umuturage", "ui.topbar.agent": "Intumwa",
    "ui.bar.steps": "Intambwe", "ui.bar.missed": "Byoroshye kwibagirwa", "ui.bar.days": "Iminsi",
    "ui.bar.some": "Bimwe", "ui.bar.free": "Ku buntu", "ui.bar.fees": "amafaranga", "ui.bar.nofees": "nta mafaranga",
    "ui.bar.progress": "Kurikirana aho ngeze",
    "ui.node.step": "Intambwe", "ui.chip.free": "Ku buntu", "ui.chip.fee": "Bisaba amafaranga", "ui.chip.missed": "byoroshye kwibagirwa",
    "ui.detail.needfirst": "Ugomba kubanza kurangiza", "ui.detail.bring": "Zana / witegure ubwawe",
    "ui.detail.goodtoknow": "Byiza kumenya", "ui.detail.opensup": "Ibi bifungura",
    "ui.detail.cost": "Igiciro", "ui.detail.howlong": "Igihe",
    "ui.detail.markdone": "✓ Shyira ku ntambwe yarangiye", "ui.detail.markundone": "↩ Garura ku itararangira",
  },
};

const CATALOGS: Record<Locale, Record<string, string>> = {
  en: { ...(en as Record<string, string>), ...UI.en },
  rw: { ...(rw as Record<string, string>), ...UI.rw },
};

interface Ctx { locale: Locale; setLocale: (l: Locale) => void; t: (key: string, fallback?: string) => string }
const LocaleContext = createContext<Ctx>({ locale: "en", setLocale: () => {}, t: (_k, f = "") => f });

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");
  const t = (key: string, fallback = "") => (CATALOGS[locale] && CATALOGS[locale][key]) || CATALOGS.en[key] || fallback;
  return <LocaleContext.Provider value={{ locale, setLocale, t }}>{children}</LocaleContext.Provider>;
}
export const useLocale = () => useContext(LocaleContext);
